DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - CSS_STYLELINT
  - HTML_DJLINT
  - JAVA_CHECKSTYLE
  - JAVA_PMD
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - SPELL_LYCHEE
  - YAML_PRETTIER
  - YAML_YAMLLINT
