spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.3
          max-tokens: 1000

  cache:
    type: simple

  datasource:
    url: jdbc:postgresql://localhost:5432/summarizer_db
    username: summarizer_user
    password: summarizer_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 24 hours

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs-generated
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs

logging:
  level:
    com.negadras.summarizer.controller.OpenApiController: DEBUG
