name: Java CI with Maven

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: summarizer-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '24'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          directory: summarizer-api # defaults.run.working-directory only affects run: commands, not uses: steps
